### ISSUE TITLE
隣り合った特定要素のmargin-top削除

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#105]
削除し忘れていたコンポーネント通しのマージン設定。

```scss
.grid {
...
  &:not(.is-gap-none) + .grid:not(.is-gap-none) {
    margin-top: 0.5em;
  }
...
}

.field {
...
  > .field + .field {
    margin-top: 0;
  }
...
}
```

存在していると `.is-space` でマージンを調整しづらいので削除。
