### ISSUE TITLE
フォーム：Selectの再設計

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#107]
![image](https://user-images.githubusercontent.com/9658016/39102712-3dfe6f2e-46e1-11e8-883e-3d4b7e951995.png)

`size` 属性に対応していなかったため修正。

- `.select` と `option` を調整する必要がある
- 引き続き `appearance` は殺さない方向で
  - その場合 `option` にCSS効かないブラウザあった気が...
- 各ブラウザでの挙動を確認

```scss
.select {
    max-width: 100%;
    /* height: calc(2.5em + 2px); */
    /* padding: 0 .75em; */
    background-color: #fff;
    border: 1px solid rgba(0,0,0,.26);
    border-radius: 2px;
    color: rgba(0,0,0,.7);
    line-height: 2.5em;
}

.select>option {
    min-height: 1.5em;
    padding: .5em .75em;
}
```

これで行ける？
