### ISSUE TITLE
Flex：フルサイズの幅がautoでリセットできない不具合の解決

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#123]
before

幅をフルサイズにしている場合に、メディアクエリでautoに戻せない。

```scss
.is-mobile-full {
    flex: 0 1 100%;
    max-width: 100%;
    width: 100%;
}

.is-tablet-auto {
    flex: 0 1 auto;
    max-width: 100%;
}
```

after

auto側に`width: auto;`を付与して固定幅をリセットさせる必要がある。

```scss
.is-mobile-full {
    flex: 0 1 100%;
    max-width: 100%;
    width: 100%;
}

.is-tablet-auto {
    flex: 0 1 auto;
    max-width: 100%;
    width: auto;
}
```

**Comment by qrac** [comment]
Flex要素のwidthは無視される仕様だった気もするが...。

**Comment by qrac** [comment]
![image](https://user-images.githubusercontent.com/9658016/43356676-01245954-92b0-11e8-943e-ea82a7aeb6b8.png)

- [Form | MUSUBii](https://qrac.github.io/musubii/documentation/form.html#field)

デベロッパーツールで検証。`full -> 0`はwidthが無視されるが、`full -> auto`はwidthが効いたまま。

**Comment by qrac** [comment]
他のフレームワークを参考にしてみる。

- Bootstrapは`flex`と`max-width`で指定している（今のMUSUBiiは近い）
  - [Grid system · Bootstrap](https://getbootstrap.com/docs/4.1/layout/grid/)
- Semantic UIは`width`のみで指定している
  - [Grid | Semantic UI](https://semantic-ui.com/collections/grid.html)
- Bulmaは`flex: none`でflexを無効にし`width`で指定している

**Comment by qrac** [comment]
## 試案

```scss
@each $key, $mediaquery in $pattern-breakpoint-mediaquery-all {
  @include mediaquery-pattern($mediaquery) {
    @for $i from 0 through $grid-split {
      @if $i == 0 {
        .is-#{$key}-#{$i} {
          flex: 1 0 0%;
        }
      } @else {
        .is-#{$key}-#{$i} {
          flex: 0 0 100% / $grid-split * $i;
          width: 100% / $grid-split * $i;
        }
      }
    }
    .is-#{$key}-full {
      flex: 0 1 100%;
      width: 100%;
    }
    .is-#{$key}-auto {
      flex: 0 1 auto;
      width: auto;
    }
  }
}
```

noneをかけるとshrinkが効かなくてfullがはみ出すため、flexは的確に指定する必要がある。

## Before

![image](https://user-images.githubusercontent.com/9658016/43357121-cd4288c4-92b7-11e8-8642-7452e8ceafd7.png)

material-iconsのボタンがfullからautoに変化できていない。

## After

![image](https://user-images.githubusercontent.com/9658016/43357131-ed8e2098-92b7-11e8-9c4b-68356e5f51cf.png)

material-iconsのボタンがfullからautoに変化できた。

## etc.

![image](https://user-images.githubusercontent.com/9658016/43357156-38e5735c-92b8-11e8-87e3-008f327b23c2.png)

![image](https://user-images.githubusercontent.com/9658016/43357174-81f268d4-92b8-11e8-8301-ae36d995a5fc.png)

グリッド分割も問題ないもよう。
