### ISSUE TITLE
Button：パーツの高さ調整

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#125]
- [フォームパーツ内の高さをline-heightで調整 · Issue #72 · qrac/musubii](https://github.com/qrac/musubii/issues/72)
- [ボタン内の高さをline-heightで調整 · Issue #70 · qrac/musubii](https://github.com/qrac/musubii/issues/70)

以前のiOSバグが解消されたため、不要なバグフィックスを取り除く。主に、line-heightで高さを保持していた部分を調整する。

**Comment by qrac** [comment]
circleボタンの高さが他よりも2px小さく揃っていなかった部分も合わせて修正。

**Comment by qrac** [comment]
## before

```scss
// .btn
$btn-padding: 0 1em !default;
$btn-line-height: 2.5em !default;
$btn-circle-border-radius: 1.25em !default;

.btn {
  ...
  &.is-circle {
    ...
    width: $btn-line-height;
    height: $btn-line-height;
    ...
  }
}
```

## After

新規変数：`$btn-circle-width` `$btn-circle-height`

```scss
$btn-padding: 0.5em 1em !default;
$btn-line-height: 1.5 !default;
$btn-circle-width: calc(2.5em + 1px * 2) !default;
$btn-circle-height: calc(2.5em + 1px * 2) !default;
$btn-circle-border-radius: 999em !default;

.btn {
  ...
  &.is-circle {
    ...
    width: $btn-circle-width;
    height: $btn-circle-height;
    ...
  }
}
```
