### ISSUE TITLE
レスポンシブの記述をUtilityとしてまとめられないか

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#13]
グリッド・ボタン・フォーム・テーブルなどのレスポンシブ化CSSは似通っているので、まとめて書くこともできるのでは？

**Comment by qrac** [comment]
グリッド以外の分割仕様では、通常は均等に分割できるが、スペースが入った瞬間に段落ちしてしまう。

**Comment by qrac** [comment]
```scss
.is-mobile-6 {
    flex: 0 0 50%;
    max-width: calc(50% - 4px);
}
```
で切り抜けられるか。
