### ISSUE TITLE
Form：Selectタグが伸びないバグ

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#133]
![image](https://user-images.githubusercontent.com/9658016/46904580-81010c00-cf21-11e8-9534-7ab6ebda8d44.png)

`select` は `.select` でラップすることで下矢印のCSS装飾を可能にした。2階層になった影響で、 `.select` を `.is-mobile-full` などで伸ばしても子要素の `select` タグが伸びない。自動的に伸縮させる。

```scss
.select > select {
    width: 100%;
}
```
