### ISSUE TITLE
WYSIWYG：リンクリバースの設定を追加

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#147]
リンクを以下のようにhoverで線が出るようオーバーライドすることが多いので、オプションで `.is-link-reverse` に切り替えられるようにする。

```scss
.wysiwyg a {
  border-bottom: none;
  &:hover {
    border-bottom: 1px solid currentColor;
  }
}
```
