### ISSUE TITLE
Grid：CSS Gridを使った実装

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#153]
![image](https://user-images.githubusercontent.com/9658016/53856404-2f166b00-4015-11e9-917b-8a5ebad944c1.png)

```scss
.grid-area {
  display: grid;
  &.is-auto {
    grid-template-columns: repeat(3, 1fr);
  }
  &.is-gap {
    gap: 0.5em;
  }
}
```

とても簡単になるので導入したいところ。

> - [CSS Grid Layout入門。対応ブラウザが出揃った新しいレイアウト仕様 - ICS MEDIA](https://ics.media/entry/15649/2)
> - [CSS Grid Layoutをガッツリ使った所感 - ICS MEDIA](https://ics.media/entry/17403)
> - [CSS Gridのgap（grid-gap）が遂にIE 11でも再現できるように。Autoprefixerが待望のアップデート - Qiita](https://qiita.com/tonkotsuboy_com/items/10fc250ac579a32e9ee9)
