### ISSUE TITLE
Box：ボックスレイアウトの追加

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#169]
![image](https://user-images.githubusercontent.com/9658016/54728406-14212a80-4bc1-11e9-959c-aca724fcb508.png)

よく使うボックス型UIのベースを追加。

`.box` `.box.is-padding-sm` `.box.is-padding-left-none` `.box.is-angle-right`など。

**Comment by qrac** [comment]
`.is-separate` で `border-top` を追加。

**Comment by qrac** [comment]
カバー要素など。

```scss
.is-cover {
  background-size: cover;
}
```
