### ISSUE TITLE
Separate：コンテンツを線で区切るClassを追加

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#181]
主に `.box` を線で区切り、アプリでよくあるリストを作る。

```scss
.is-separate > *:not(:first-child) {
  border-top: 1px solid $grey-100;
}
```
