### ISSUE TITLE
Button：AngleのUp版・Down版を追加

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#220]
#172 への追加。

左右に設置したAngleを上に向けたり下に向けたり。アコーディオン系のUI用。

```scss
.button {
  &.is-angle-left,
  &.is-angle-right {
    &.is-angle-up {
      &:after {
        transform: translateY(-30%) rotate(-45deg);
      }
    }
    &.is-angle-down {
      &:after {
        transform: translateY(-70%) rotate(135deg);
      }
    }
  }
}
```
