### ISSUE TITLE
セレクトボックスの矢印をクリックした場合に反応しない

### ISSUE THREAD

**Issue by takamoso** [qrac/musubii#243]
セレクトボックスの矢印部分を擬似要素で描画していると思いますが、その部分をクリックしてもセレクトボックスが反応しません。矢印部分が小さいため、たまたまクリックしないと気づかないかもしれませんが...

```css
.select:not(.is-multiple):after {
  pointer-events: none;
}
```

`pointer-events` プロパティで制御しておくといいかもしれないです。
