### ISSUE TITLE
WYSIWYG：別のエレメントに依存していた変数を分離

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#248]
```scss
@mixin musubii-style-wysiwyg-text-link() {
  a {
    cursor: pointer;
    color: $wysiwyg-link-text-color;
    @if $text-link-border-change-underline == true {
      text-decoration: underline;
      &:hover {
        text-decoration: none;
      }
    } @else {
      border-bottom: $text-link-border-bottom-width
        $text-link-border-bottom-style
        currentColor;
      &:hover,
      &:active {
        border-bottom-color: transparent;
      }
    }
  }
}
```

など。上記は `$text-xxx` の変数が含まれたSCSSファイルを読み込んでいないと、`configs` + `_wisywig.scss` といったミニマムな使い方ができなくなる。

`$wysiwyg-xxx` の変数を個別に設定する。
