### ISSUE TITLE
Button：役割ごとのFloating設定を可能にする

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#262]
![image](https://user-images.githubusercontent.com/9658016/72492770-c6696300-3861-11ea-8658-7e1e4af7536d.png)

ボタンに付与するBox Shadow（主に色）は、ボタンスタイルに応じたものを作る場合が多くなっている。

現状の `is-floating` は、Box Shadow自体をSCSS変数でカスタマイズできるが、`.is-primary.is-floating` だけの色を変えるなどの細かい設定はできない。

そこで、デフォルトの変数と役割ごとの変数を分離し、一括編集と詳細編集の両方を可能にする。

```scss
// ex:
$default-floating-shadow: 0 4px 12px 0 red;
$primary-floating-shadow: $default-floating-shadow;

.button.is-primary {
  box-shadow: $primary-floating-shadow;
}
```
