### ISSUE TITLE
List：四角と米印のスタイルを追加

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#266]
リスト装飾 `list-style-type` は `disc` `circle` `decimal` では足らない部分が出ている。オーバーライド・CSS装飾の頻度を減らすためにもバリュエーションを増やす。

また、`list-style-type` には `<string>` 形式も使えるため、`.is-note` の使い方も再検討する。

`list-style-image` は汎用的なスタイルが作れれば実装。

**Comment by qrac** [comment]
![image](https://user-images.githubusercontent.com/9658016/72726082-d028f880-3bca-11ea-83f4-badbf6e590de.png)

`.is-square` `.is-kome`

**Comment by qrac** [comment]
`$list-kome-item-list-style: "\203B"outside !default;` だとPrettierがoutsideとの間を詰めてしまうため、`$list-kome-item-list-style: "※" outside !default;` にする。

また、日本語がCSS内に含まれた影響で `@charset "UTF-8";` が追加されてしまう。

**Comment by qrac** [comment]
Sassのデフォルト関数などを駆使して回避する。

> [java - SASS is prepending unicode content with backslash (\) - Stack Overflow](https://stackoverflow.com/questions/40375261/sass-is-prepending-unicode-content-with-backslash)

```scss
@function unicode($str) {
  @return unquote("\"")+unquote(str-insert($str, "\\", 1))+unquote("\"");
}

$list-kome-unicode: unicode("203B") !default;
$list-kome-item-list-style: $list-kome-unicode outside !default;
```

または

```scss
$list-kome-unicode: unquote('"') + unquote(str-insert("203B", "\\", 1)) + unquote('"') !default;
$list-kome-item-list-style: $list-kome-unicode outside !default;
```

今回はここ以外でFunctionを使うことがないので、後者の通り関数を変数内に埋め込んだ。
