### ISSUE TITLE
ボタンCSSの見直し

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#27]
使用頻度の下がってきているFlatタイプの削除。

```scss
.btn.is-flat {
  border-bottom: 3px solid $dark-7;
  transition: none;
  &:hover {
    border-bottom-width: 2px;
    margin-top: 1px;
  }
  &:active {
    border-bottom: 1px solid transparent;
    margin-top: 2px;
  }
  &.is-disable,
  &.is-disable:hover,
  &.is-disable:active {
    border-bottom: 3px solid $dark-9;
    margin-top: 0;
  }
}
```

**Comment by qrac** [comment]
ボタン通しのスペーシングをデフォルト化

before

```scss
@for $i from 1 through 9 {
  .btns.is-space-#{$i} {
    margin-bottom: $i * -4px;
  }
  .btns.is-space-#{$i} > * {
    margin-right: $i * 4px;
    margin-bottom: $i * 4px;
  }
}
```

after

```scss
.btns {
  margin-left: -0.25em;
  > .btn {
    margin-left: 0.25em;
  }
}
```

**Comment by qrac** [comment]
`.btns`のフレックスレイアウトをグリッドに合わせる。

before

```scss
.btns {
  &.is-left {
    justify-content: flex-start;
  }
  &.is-center {
    justify-content: center;
  }
  &.is-right {
    justify-content: flex-end;
  }
  &.is-middle {
    align-items: center;
  }
}
```

after

```scss
.btns {
  &.is-middle {
    align-items: center;
  }
  &.is-bottom {
    align-items: flex-end;
  }
  &.is-center {
    justify-content: center;
  }
  &.is-right {
    justify-content: flex-end;
  }
  &.is-between {
    justify-content: space-between;
  }
  &.is-around {
    justify-content: space-around;
  }
}
```

**Comment by qrac** [comment]
ボタンのフローティングバリュエーションを1パターンに変更。

before

```scss
$shadow-floating-1:
  0 1px 1.5px 0 rgba(0,0,0,.12),
  0 1px 1px 0 rgba(0,0,0,.24) !default;

$shadow-floating-2:
  0 2px 2px 0 rgba(0,0,0,.14),
  0 3px 1px -2px rgba(0,0,0,.2),
  0 1px 5px 0 rgba(0,0,0,.12) !default;

$shadow-floating-active:
  0 4px 5px 0 rgba(0,0,0,.14),
  0 1px 10px 0 rgba(0,0,0,.12),
  0 2px 4px -1px rgba(0,0,0,.2) !default;

$shadow-floating-3:
  0 1px 3px 0 rgba(0, 0, 0, 0.24) !default;

$shadow-floating-3-hover:
  0 4px 12px 0 rgba(0, 0, 0, 0.24) !default;

.btn.is-floating-1:not(.is-disable) {
  box-shadow: $shadow-floating-1;
  &:active {
    box-shadow: $shadow-floating-active;
  }
}

.btn.is-floating-2:not(.is-disable) {
  box-shadow: $shadow-floating-2;
  &:active {
    box-shadow: $shadow-floating-active;
  }
}

.btn.is-floating-3:not(.is-disable) {
  box-shadow: $shadow-floating-3;
  &:hover,
  &:active {
    box-shadow: $shadow-floating-3-hover;
  }
}
```

after

```scss
$shadow-btn-floating:
  0 1px 3px 0 rgba(0, 0, 0, 0.24) !default;

$shadow-btn-floating-hover:
  0 4px 12px 0 rgba(0, 0, 0, 0.24) !default;

.btn.is-floating:not(.is-disable) {
  box-shadow: $shadow-btn-floating;
  &:hover,
  &:active {
    box-shadow: $shadow-btn-floating-hover;
  }
}
```

**Comment by qrac** [comment]
`transition`を0.2sから0.15sに変更。

**Comment by qrac** [comment]
不要な`text-align: center;`を削除。

**Comment by qrac** [comment]
ボタンのレスポンシブ可変からtouch, landscape, portraitを削除。

```scss
@include touch {
  .btns > .btn.is-touch-0 {
    flex: 1 0 0%;
    max-width: 100%;
  }
  .btns > .btn.is-touch-full {
    flex: 0 0 100%;
    max-width: 100%;
  }
  .btns > .btn.is-touch-auto {
    flex: 0 1 auto;
    max-width: 100%;
  }
}

@include landscape {
  .btns > .btn.is-landscape-0 {
    flex: 1 0 0%;
    max-width: 100%;
  }
  .btns > .btn.is-landscape-full {
    flex: 0 0 100%;
    max-width: 100%;
  }
  .btns > .btn.is-landscape-auto {
    flex: 0 1 auto;
    max-width: 100%;
  }
}

@include portrait {
  .btns > .btn.is-portrait-0 {
    flex: 1 0 0%;
    max-width: 100%;
  }
  .btns > .btn.is-portrait-full {
    flex: 0 0 100%;
    max-width: 100%;
  }
  .btns > .btn.is-portrait-auto {
    flex: 0 1 auto;
    max-width: 100%;
  }
}
```

**Comment by qrac** [comment]
`button`や`input`をflexboxで作るとiOSで`justify-content: center;`ので、inline-blockで作る。

before

<img width="497" alt="2017-05-01 21 41 19" src="https://cloud.githubusercontent.com/assets/9658016/25579962/91e08660-2eb7-11e7-8e13-1ce6c477f3a7.png">

```scss
.btn {
  &.is-circle {
    display: inline-flex;
    justify-content: center;
    align-items: center;
    width: 2.5em;
    height: 2.5em;
    padding: 0;
    border-radius: 9999em;
  }
}
```

after

<img width="475" alt="2017-05-01 21 41 37" src="https://cloud.githubusercontent.com/assets/9658016/25579967/9c20f38a-2eb7-11e7-9e80-2dd41f05ada4.png">

```scss
.btn {
  &.is-circle {
    position: relative;
    width: 2.5em;
    height: 2.5em;
    padding: 0;
    border-radius: 999em;
  }
  &.is-circle > * {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
  }
}
```
