### ISSUE TITLE
Bases：Resetのhtmlからscrollを削除

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#275]
[htmlからscrollを削除 · Issue #24 · qrac/shitajicss](https://github.com/qrac/shitajicss/issues/24) と同一内容。

```scss
html {
  overflow-y: scroll;
}
```

古いブラウザのスクロールバー関係か何かで入れたCSS。現在のnormarize.css・sanitize.css・ress.cssには無い。これがあるとモーダルを [body-scroll-lock](https://github.com/willmcpo/body-scroll-lock) などで作るときにモーダル以外を固定できなくなるので、削除する。
