### ISSUE TITLE
テーブルCSSの見直し

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#28]
幅の指定はHTMLもしくはプロジェクトごとのCSSにゆだねるので削除。

```scss
@for $i from 1 through $split-table {
  .table .box.is-width-#{$i} {
    width: 100% / $split-table * $i;
  }
}
```

**Comment by qrac** [comment]
テーブルの着色を簡略化。

before

```scss
.table .box {
  &.is-paint-1 {
    background-color: $cyan-100;
  }
  &.is-paint-2 {
    background-color: $cyan-200;
    color: $light;
  }
  &.is-paint-3 {
    background-color: $cyan-300;
    color: $light;
  }
  &.is-paint-4 {
    background-color: $cyan-400;
    color: $light;
  }
  &.is-paint,
  &.is-paint-5 {
    background-color: $cyan-500;
    color: $light;
  }
  &.is-paint-6 {
    background-color: $cyan-600;
    color: $light;
  }
  &.is-paint-7 {
    background-color: $cyan-700;
    color: $light;
  }
  &.is-paint-8 {
    background-color: $cyan-800;
    color: $light;
  }
  &.is-paint-9 {
    background-color: $cyan-900;
    color: $light;
  }
  &.is-stripe {
    background-color: $grey-100;
  }
  &.is-spot {
    background-color: $yellow-200;
  }
  &.is-danger {
    background-color: $red-100;
  }
}
```

after

```scss
.table * {
  &.is-paint {
    background-color: $cyan-500;
    color: $light;
  }
  &.is-stripe {
    background-color: $grey-100;
  }
  &.is-spot {
    background-color: $yellow-200;
  }
  &.is-danger {
    background-color: $red-100;
  }
}
```
