### ISSUE TITLE
フォームCSSの見直し

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#29]
今一度、ブラウザデフォルトスタイルの確認を。（※差異はブラウザリロードで解決）

<img width="346" alt="2017-05-02 14 01 18" src="https://cloud.githubusercontent.com/assets/9658016/25604731/afc48e36-2f40-11e7-9c56-0eb68af52187.png">

<img width="313" alt="2017-05-02 14 02 06" src="https://cloud.githubusercontent.com/assets/9658016/25604732/afc714c6-2f40-11e7-8f21-50231360f9fd.png">

**Comment by qrac** [comment]
固定値のスペーシング設定を削除。

```scss
@for $i from 1 through 9 {
  .field.is-space-#{$i} {
    margin-bottom: $i * -4px;
  }
  .field.is-space-#{$i} > * {
    margin-right: $i * 4px;
    margin-bottom: $i * 4px;
  }
  .field.is-space-#{$i} > .field {
    margin-bottom: 0;
  }
}
```

**Comment by qrac** [comment]
`.field`の設定を`.btns`と合わせる。

before

```scss
.field {
  display: flex;
  flex-wrap: wrap;
  > .field + .field {
    margin-top: 0;
  }
  &.is-left {
    justify-content: flex-start;
  }
  &.is-center {
    justify-content: center;
  }
  &.is-right {
    justify-content: flex-end;
  }
  &.is-middle {
    align-items: center;
  }
}
```

after

```scss
.field {
  display: flex;
  flex-wrap: wrap;
  margin-left: -0.5em;
  margin-bottom: -0.5em;
  > * {
    margin-left: 0.5em;
    margin-bottom: 0.5em;
  }
  > .field {
    display: inline-flex;
  }
  > .field + .field {
    margin-top: 0;
  }
  &.is-middle {
    align-items: center;
  }
  &.is-bottom {
    align-items: flex-end;
  }
  &.is-center {
    justify-content: center;
  }
  &.is-right {
    justify-content: flex-end;
  }
  &.is-between {
    justify-content: space-between;
  }
  &.is-around {
    justify-content: space-around;
  }
}
```

**Comment by qrac** [comment]
touch, landscape, portraitのレスポンシブ設定を削除。

```scss
@include touch {
  .field > *.is-touch-0 {
    flex: 1 0 0%;
    max-width: 100%;
  }
  .field > *.is-touch-full {
    flex: 0 0 100%;
    max-width: 100%;
  }
  .field > *.is-touch-auto {
    flex: 0 1 auto;
    max-width: 100%;
  }
}

@include landscape {
  .field > *.is-landscape-0 {
    flex: 1 0 0%;
    max-width: 100%;
  }
  .field > *.is-landscape-full {
    flex: 0 0 100%;
    max-width: 100%;
  }
  .field > *.is-landscape-auto {
    flex: 0 1 auto;
    max-width: 100%;
  }
}

@include portrait {
  .field > *.is-portrait-0 {
    flex: 1 0 0%;
    max-width: 100%;
  }
  .field > *.is-portrait-full {
    flex: 0 0 100%;
    max-width: 100%;
  }
  .field > *.is-portrait-auto {
    flex: 0 1 auto;
    max-width: 100%;
  }
}
```
