### ISSUE TITLE
select[multiple]が無い

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#3]
```scss
.select[multiple] {
  height: auto;
}
```

**Comment by qrac** [comment]
multipleはoptionにpaddingを。

**Comment by qrac** [comment]
```scss
.select {
  max-width: 100%;
  height: 2.5em;
  background: $light;
  border: 1px solid $dark-6;
  border-radius: 2px;
  padding: calc(0.5em - 1.5px) 0.75em;
  &[multiple] {
    height: auto;
    padding: 0;
    > option {
      padding: 0.5em 0.75em;
    }
  }
  &[disabled] {
    background: $grey-3;
    color: $dark-6;
  }
  &[readonly] {
    background: $grey-2;
  }
}
```
