### ISSUE TITLE
Space：ネガティブマージン付きclassを追加

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#302]
`is-space-right-(xxxx) is-margin-right-minus-(xxxx)` の記述が冗長で使いにくいため、ネガティブマージンを含んだ単一classを作成する。

```css
.is-space-horizontal-xs {
  margin-left: -8px;
}

.is-space-horizontal-xs > * {
  margin-left: 8px;
}

.is-space-vertical-xs {
  margin-bottom: -8px;
}

.is-space-vertical-xs > * {
  margin-bottom: 8px;
}
```
