### ISSUE TITLE
ユーティリティCSSの調整

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#32]
不要なCSSを削除。

```scss
* {
  &.is-small {
    font-size: 80%;
  }
  &.is-super {
    vertical-align: super;
    font-size: 70%;
  }
  &.is-none-touch {
    @include touch {
      display: none;
    }
  }
  &.is-none-landscape {
    @include landscape {
      display: none;
    }
  }
  &.is-none-portrait {
    @include portrait {
      display: none;
    }
  }
}
```

**Comment by qrac** [comment]
yakuhanjpのクラスを忘れずに。

**Comment by qrac** [comment]
位置を変更するユーティリティが`.grid` `.btns` `field`のCSSとかぶらないようにする。

```scss
*:not(.grid):not(.btns):not(.field) {
  &.is-left {
    text-align: left;
  }
  &.is-center {
    text-align: center;
  }
  &.is-right {
    text-align: right;
  }
  &.is-baseline {
    vertical-align: baseline;
  }
  &.is-top {
    vertical-align: top;
  }
  &.is-middle {
    vertical-align: middle;
  }
  &.is-bottom {
    vertical-align: bottom;
  }
}
```
