### ISSUE TITLE
フォーム用ボタンの文字色調整

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#36]
<img width="530" alt="2017-05-07 9 45 16" src="https://cloud.githubusercontent.com/assets/9658016/25776993/04b978f8-330a-11e7-8256-c933ee3bbe07.png">

<img width="366" alt="2017-05-07 9 24 53" src="https://cloud.githubusercontent.com/assets/9658016/25776929/829f0812-3307-11e7-875d-b50feedd3497.png">

↑インプット・セレクト・ボタンのデフォルト文字色が黒すぎる。

<img width="534" alt="2017-05-07 9 45 25" src="https://cloud.githubusercontent.com/assets/9658016/25776995/0fea024c-330a-11e7-83aa-6d0bed12c2ef.png">

<img width="366" alt="2017-05-07 9 25 12" src="https://cloud.githubusercontent.com/assets/9658016/25776930/82ae241e-3307-11e7-952c-4bb1ab4114f4.png">

↑他の文字色に合わせる。

**Comment by qrac** [comment]
インプットボタンがv2.0.1でも改善されていない。

**Comment by qrac** [comment]
ボタン側で改善。

```scss
.btn {
  &[type="button"],
  &[type="reset"],
  &[type="submit"] {
    color: $dark-2;
  }
}
```
