### ISSUE TITLE
グリッド溝を消すクラス追加

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#38]
`.grid.is-gap-none`・`.grid:not(.is-gap-none)`

**Comment by qrac** [comment]
```scss
.grid {
  &:not(.is-gap-none) {
    margin-left: -0.5em;
    margin-bottom: -0.5em;
  }
  &:not(.is-gap-none) > .col {
    padding-left: 0.5em;
    padding-bottom: 0.5em;
  }
  &:not(.is-gap-none) + .grid:not(.is-gap-none) {
    margin-top: 0.5em;
  }
}
```
