### ISSUE TITLE
リンクの下線調整

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#39]
IE11だとinheritでテキストの色が引き継がれない。currentColorを使う。

before

```scss
.text.is-link {
  cursor: pointer;
  border-bottom: 1px solid;
  &:hover {
    border-bottom-color: transparent;
  }
}

.text.is-link-reverse {
  cursor: pointer;
  border-bottom: 1px solid transparent;
  &:hover {
    border-color: inherit;
  }
}

.wysiwyg a {
  cursor: pointer;
  color: $primary;
  border-bottom: 1px solid;
  &:hover,
  &:active {
    border-bottom-color: transparent;
  }
}
```

after

```scss
.text.is-link {
  cursor: pointer;
  border-bottom: 1px solid currentColor;
  &:hover {
    border-bottom-color: transparent;
  }
}

.text.is-link-reverse {
  cursor: pointer;
  border-bottom: 1px solid transparent;
  &:hover {
    border-color: currentColor;
  }
}

.wysiwyg a {
  cursor: pointer;
  color: $primary;
  border-bottom: 1px solid currentColor;
  &:hover {
    border-bottom-color: transparent;
  }
}
```
