### ISSUE TITLE
WYSIWYGのcodeサイズ調整

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#40]
サイズ指定を間違えているので、通常の`code`より小さくなってしまっている。

before

```scss
.wysiwyg :not(pre) code {
  font-size: 0.765em;
}
```

after

```scss
.wysiwyg :not(pre) code {
  font-size: 0.875em;
}
```
