### ISSUE TITLE
WYSIWYG imgタグ周りのマージン設定

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#42]
書くのを忘れていた。_space.scssのWYSIWYG部分を更新する。

```scss
.wysiwyg {
  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    + h1,
    + h2,
    + h3,
    + h4,
    + h5,
    + h6 {
      margin-top: 1em;
    }
    + img,
    + p,
    + blockquote,
    + pre,
    + ul,
    + ol,
    + table,
    + hr {
      margin-top: 1em;
    }
  }
  img,
  p,
  blockquote,
  pre,
  ul,
  ol,
  table,
  hr {
    + h1,
    + h2,
    + h3,
    + h4,
    + h5,
    + h6 {
      margin-top: 2em;
    }
    + img,
    + p,
    + blockquote,
    + pre,
    + ul,
    + ol,
    + table,
    + hr {
      margin-top: 1em;
    }
  }
}
```
