### ISSUE TITLE
テーブルのボーダーを調整

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#46]
連結の仕方によってはボーダーが2重になったり破損したりしているので調整。

![musubii-table-issue-17060101](https://cloud.githubusercontent.com/assets/9658016/26671414/5adb02f2-46f0-11e7-913d-b3cae59db2a4.png)

![musubii-table-issue-17060102](https://cloud.githubusercontent.com/assets/9658016/26671415/5ae3dd82-46f0-11e7-903f-b08e27067276.png)

**Comment by qrac** [comment]
テスト

[MUSUBii Table Test](https://codepen.io/qrac/pen/NgKWyq)

**Comment by qrac** [comment]
線に透明度があると重ねた時に色が足されてしまうので、透過線は厳しいかも。

```css
table {
  border-spacing: 0;
  border-collapse: collapse;
}
```

**Comment by qrac** [comment]
他のフレームワークを確認。

- [Tables · Bootstrap](https://v4-alpha.getbootstrap.com/content/tables/)
- [Table | Semantic UI](https://semantic-ui.com/collections/table.html)
- [Tables | Foundation for Sites 6 Docs](http://foundation.zurb.com/sites/docs/table.html)
- [Bulma: a modern CSS framework based on Flexbox](http://bulma.io/documentation/elements/table/)

**Comment by qrac** [comment]
Semantic UIも縦の連結でボーダーが消える...。2行目以降は2列目の`td`が`:first-child`になってしまうため。

<img width="685" alt="2017-06-01 22 01 07" src="https://cloud.githubusercontent.com/assets/9658016/26680896/13ddb932-4716-11e7-8a5d-4c185727f2e8.png">

**Comment by qrac** [comment]
線を重ねる場合の書き方で統一。

```scss
.table {
  width: 100%;
  background-color: $light;
  border-collapse: collapse;
  border-spacing: 0;
  th,
  td {
    padding: 0.75em 1em;
    vertical-align: top;
  }
  &.is-middle th,
  &.is-middle td {
    vertical-align: middle;
  }
  > thead > tr:last-child > th {
    border-bottom: 2px solid $blue-grey-100;
  }
}

.table.is-line {
  border-top: 1px solid $blue-grey-100;
  border-bottom: 1px solid $blue-grey-100;
  > tbody > tr:not(:first-child) > * {
    border-top: 1px solid $blue-grey-100;
  }
}

.table.is-outline {
  border: 1px solid $blue-grey-100;
}

.table.is-border {
  border: 1px solid $blue-grey-100;
  th,
  td {
    border: 1px solid $blue-grey-100;
  }
}
```
