### ISSUE TITLE
不要なutilityを除去

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#47]
前回のアップデートで消している予定だった。

```scss
* {
  &.is-none-touch {
    @include touch {
      display: none;
    }
  }
  &.is-none-landscape {
    @include landscape {
      display: none;
    }
  }
  &.is-none-portrait {
    @include portrait {
      display: none;
    }
  }
}
```
