### ISSUE TITLE
全称セレクタの削減

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#54]
[Webフロントエンド ハイパフォーマンス チューニング | 久保田 光則 |本 | 通販 | Amazon](https://www.amazon.co.jp/dp/4774189677)

最新の情報を確認し、パフォーマンスチェックを再度施す。

**Comment by qrac** [comment]
スコープが甘いCSS、および単純に全称セレクタが出力されているCSS。

```css
.table *.is-paint {
  background-color: #1cb4c7;
  color: #ffffff;
}

.table *.is-stripe {
  background-color: whitesmoke;
}

.table *.is-spot {
  background-color: #f5eeb7;
}

.table *.is-danger {
  background-color: #fdd9dd;
}

.field > * {
  margin-left: 0.5em;
  margin-bottom: 0.5em;
}

.field > *.is-mobile-0 {
  -webkit-box-flex: 1;
  flex: 1 0 auto;
  max-width: 100%;
}

.field > *.is-mobile-full {
  -webkit-box-flex: 0;
  flex: 0 1 100%;
  max-width: 100%;
}

.field > *.is-mobile-auto {
  -webkit-box-flex: 0;
  flex: 0 1 auto;
  max-width: 100%;
}

@media screen and (min-width: 576px) {
  .field > *.is-fablet-0 {
    -webkit-box-flex: 1;
    flex: 1 0 auto;
    max-width: 100%;
  }
  .field > *.is-fablet-full {
    -webkit-box-flex: 0;
    flex: 0 1 100%;
    max-width: 100%;
  }
  .field > *.is-fablet-auto {
    -webkit-box-flex: 0;
    flex: 0 1 auto;
    max-width: 100%;
  }
}

@media screen and (min-width: 768px) {
  .field > *.is-touch-0 {
    -webkit-box-flex: 1;
    flex: 1 0 auto;
    max-width: 100%;
  }
  .field > *.is-touch-full {
    -webkit-box-flex: 0;
    flex: 0 1 100%;
    max-width: 100%;
  }
  .field > *.is-touch-auto {
    -webkit-box-flex: 0;
    flex: 0 1 auto;
    max-width: 100%;
  }
}

@media screen and (min-width: 992px) {
  .field > *.is-desktop-0 {
    -webkit-box-flex: 1;
    flex: 1 0 auto;
    max-width: 100%;
  }
  .field > *.is-desktop-full {
    -webkit-box-flex: 0;
    flex: 0 1 100%;
    max-width: 100%;
  }
  .field > *.is-desktop-auto {
    -webkit-box-flex: 0;
    flex: 0 1 auto;
    max-width: 100%;
  }
}

@media screen and (min-width: 1200px) {
  .field > *.is-wide-0 {
    -webkit-box-flex: 1;
    flex: 1 0 auto;
    max-width: 100%;
  }
  .field > *.is-wide-full {
    -webkit-box-flex: 0;
    flex: 0 1 100%;
    max-width: 100%;
  }
  .field > *.is-wide-auto {
    -webkit-box-flex: 0;
    flex: 0 1 auto;
    max-width: 100%;
  }
}

.alert.is-primary * {
  color: #0ea1b3;
}

.alert.is-info * {
  color: #498dc9;
}

.alert.is-success * {
  color: #5a995c;
}

.alert.is-warning * {
  color: rgba(0, 0, 0, 0.5);
}

.alert.is-danger * {
  color: #d75653;
}

*.is-xxl {
  font-size: 200%;
}

*.is-xl {
  font-size: 150%;
}

*.is-lg {
  font-size: 125%;
}

*.is-md {
  font-size: 100%;
}

*.is-sm {
  font-size: 87.5%;
}

*.is-xs {
  font-size: 75%;
}

*.is-xxs {
  font-size: 62.5%;
}

*.is-dark {
  color: #000000;
}

*.is-dark-1 {
  color: rgba(0, 0, 0, 0.87);
}

*.is-dark-2 {
  color: rgba(0, 0, 0, 0.7);
}

*.is-dark-3 {
  color: rgba(0, 0, 0, 0.6);
}

*.is-dark-4 {
  color: rgba(0, 0, 0, 0.5);
}

*.is-dark-5 {
  color: rgba(0, 0, 0, 0.4);
}

*.is-dark-6 {
  color: rgba(0, 0, 0, 0.26);
}

*.is-dark-7 {
  color: rgba(0, 0, 0, 0.15);
}

*.is-dark-8 {
  color: rgba(0, 0, 0, 0.12);
}

*.is-dark-9 {
  color: rgba(0, 0, 0, 0.05);
}

*.is-light {
  color: #ffffff;
}

*.is-light-1 {
  color: rgba(255, 255, 255, 0.87);
}

*.is-light-2 {
  color: rgba(255, 255, 255, 0.7);
}

*.is-light-3 {
  color: rgba(255, 255, 255, 0.6);
}

*.is-light-4 {
  color: rgba(255, 255, 255, 0.5);
}

*.is-light-5 {
  color: rgba(255, 255, 255, 0.4);
}

*.is-light-6 {
  color: rgba(255, 255, 255, 0.26);
}

*.is-light-7 {
  color: rgba(255, 255, 255, 0.15);
}

*.is-light-8 {
  color: rgba(255, 255, 255, 0.12);
}

*.is-light-9 {
  color: rgba(255, 255, 255, 0.05);
}

*.is-primary:not(.btn) {
  color: #1cb4c7;
}

*.is-info:not(.btn) {
  color: #4b9ad8;
}

*.is-success:not(.btn) {
  color: #1bbc5e;
}

*.is-warning:not(.btn) {
  color: #e8db61;
}

*.is-danger:not(.btn) {
  color: #e65d53;
}

*.is-yakuhanjp {
  font-family: -apple-system, BlinkMacSystemFont, YakuHanJP, "Hiragino Sans", Meiryo, sans-serif;
}

*.is-yakuhanjps {
  font-family: -apple-system, BlinkMacSystemFont, YakuHanJPs, "Hiragino Sans", Meiryo, sans-serif;
}

*.is-normal {
  font-weight: 300;
}

*.is-strong {
  font-weight: 700;
}

*.is-weight-100 {
  font-weight: 100;
}

*.is-weight-200 {
  font-weight: 200;
}

*.is-weight-300 {
  font-weight: 300;
}

*.is-weight-400 {
  font-weight: 400;
}

*.is-weight-500 {
  font-weight: 500;
}

*.is-weight-700 {
  font-weight: 700;
}

*.is-weight-900 {
  font-weight: 900;
}

*.is-italic {
  font-style: italic;
}

*.is-delete {
  text-decoration: line-through;
}

*.is-capitalize {
  text-transform: capitalize;
}

*.is-lowercase {
  text-transform: lowercase;
}

*.is-uppercase {
  text-transform: uppercase;
}

*:not(.grid):not(.btns):not(.field).is-left {
  text-align: left;
}

*:not(.grid):not(.btns):not(.field).is-center {
  text-align: center;
}

*:not(.grid):not(.btns):not(.field).is-right {
  text-align: right;
}

*:not(.grid):not(.btns):not(.field).is-baseline {
  vertical-align: baseline;
}

*:not(.grid):not(.btns):not(.field).is-top {
  vertical-align: top;
}

*:not(.grid):not(.btns):not(.field).is-middle {
  vertical-align: middle;
}

*:not(.grid):not(.btns):not(.field).is-bottom {
  vertical-align: bottom;
}

*.is-nowrap {
  white-space: nowrap;
}

*.is-break {
  word-break: break-all;
}

*.is-centering {
  margin: 0 auto;
}

*.is-scroll-x {
  overflow: hidden;
  overflow-x: auto;
  -webkit-overflow-scrolling: touch;
}

*.is-ellipsis {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

*.is-block {
  display: block;
}

*.is-inline {
  display: inline;
}

*.is-inline-block {
  display: inline-block;
}

*.is-none, *.is-none-mobile {
  display: none;
}

@media screen and (min-width: 576px) {
  *.is-none-fablet {
    display: none;
  }
}

@media screen and (min-width: 768px) {
  *.is-none-tablet {
    display: none;
  }
}

@media screen and (min-width: 992px) {
  *.is-none-desktop {
    display: none;
  }
}

@media screen and (min-width: 1200px) {
  *.is-none-wide {
    display: none;
  }
}

@media screen and (max-width: 575px) {
  *.is-none-mobile-only {
    display: none;
  }
}

@media screen and (min-width: 576px) and (max-width: 767px) {
  *.is-none-fablet-only {
    display: none;
  }
}

@media screen and (min-width: 768px) and (max-width: 991px) {
  *.is-none-tablet-only {
    display: none;
  }
}

@media screen and (min-width: 992px) and (max-width: 1199px) {
  *.is-none-desktop-only {
    display: none;
  }
}

*.is-clearfix:after {
  display: block;
  content: "";
  clear: both;
}
```
