### ISSUE TITLE
コード装飾の調整

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#56]
`:not(.pre) .code`は効いていない。親要素を探せていない？
効かせるとすれば、`:not(.pre) > .code`とする必要がある。

`.code`とし、オーバーライド前提にするか、
`:not(.pre) > .code`としCSSを明確に分ける。

WYSIWYGの`pre``code`も確認。

**Comment by qrac** [comment]
pre要素内のコードはブロック要素にしないとpaddingが効かない。
MUSUBii DEMO内のコードはhighlight.jsがブロック要素にしている。

```
.pre>.code {
    display: block;
}
```

**Comment by qrac** [comment]
`.code`の角丸もボタンと同じで相対的にしていいのでは？

**Comment by qrac** [comment]
```scss
.pre,
.code {
  color: $indigo-500;
  font-family: $font-mono;
}

:not(.pre) {
  > .code {
    padding: 0.2em 0.5em;
    background-color: $grey-100;
    border-radius: 0.1875em;
    font-size: 0.875em;
    word-break: break-all;
  }
}

.pre {
  background-color: $grey-100;
  border-radius: 0.125em;
  white-space: pre;
  word-wrap: normal;
  overflow: hidden;
  overflow-x: auto;
  -webkit-overflow-scrolling: touch;
  > .code {
    display: block;
    padding: 1.25em 1.5em;
  }
}
```

```scss
.wysiwyg code,
.wysiwyg pre {
  color: $indigo-500;
  font-family: $font-mono;
}

.wysiwyg :not(pre) {
  > code {
    padding: 0.2em 0.5em;
    background-color: $grey-100;
    border-radius: 0.1875em;
    font-size: 0.875em;
    word-break: break-all;
  }
}

.wysiwyg pre {
  background-color: $grey-100;
  border-radius: 0.125em;
  font-size: 0.875em;
  white-space: pre;
  word-wrap: normal;
  overflow: hidden;
  overflow-x: auto;
  -webkit-overflow-scrolling: touch;
  > code {
    display: block;
    padding: 1.25em 1.5em;
  }
}
```
