### ISSUE TITLE
引用枠の調整

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#57]
サイズの相対化を検討。
WYSIWYG内の`blockquote`も同じく。

**Comment by qrac** [comment]
最終案

```scss
.blockquote {
  background-color: $grey-100;
  border-left: 0.5em solid $dark-9;
  border-radius: 0.125em;
  padding: 1.5em;
}
```

```scss
.wysiwyg blockquote {
  background-color: $grey-100;
  border-left: 0.5em solid $dark-9;
  border-radius: 0.125em;
  padding: 1.5em;
  font-size: 0.875em;
}
```
