### ISSUE TITLE
ボタンとフォームのレスポンシブclass名修正

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#58]
ボタン間違え

```scss
@include tablet {
  .btns > .btn.is-touch-0 {
    flex: 1 0 auto;
    max-width: 100%;
  }
  .btns > .btn.is-touch-full {
    flex: 0 1 100%;
    max-width: 100%;
  }
  .btns > .btn.is-touch-auto {
    flex: 0 1 auto;
    max-width: 100%;
  }
}
```

フォーム間違え

```scss
@include tablet {
  .field > .is-touch-0 {
    flex: 1 0 auto;
    max-width: 100%;
  }
  .field > .is-touch-full {
    flex: 0 1 100%;
    max-width: 100%;
  }
  .field > .is-touch-auto {
    flex: 0 1 auto;
    max-width: 100%;
  }
}
```

**Comment by qrac** [comment]
`touch`ではなく`tablet`

ボタン

```scss
@include tablet {
  .btns > .btn.is-tablet-0 {
    flex: 1 0 auto;
    max-width: 100%;
  }
  .btns > .btn.is-tablet-full {
    flex: 0 1 100%;
    max-width: 100%;
  }
  .btns > .btn.is-tablet-auto {
    flex: 0 1 auto;
    max-width: 100%;
  }
}
```

フォーム間違え

```scss
@include tablet {
  .field > .is-touch-0 {
    flex: 1 0 auto;
    max-width: 100%;
  }
  .field > .is-tablet-full {
    flex: 0 1 100%;
    max-width: 100%;
  }
  .field > .is-tablet-auto {
    flex: 0 1 auto;
    max-width: 100%;
  }
}
```
