### ISSUE TITLE
ボタンとフォームのフルサイズ修正

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#64]
before

要素がひとつの場合右端に隙間ができる？

```scss
.btns>.btn.is-full, .btns>.btn.is-mobile-full {
  -webkit-box-flex: 0;
  flex: 0 1 100%;
  max-width: 100%;
}
```

after

```scss
.btns>.btn.is-full, .btns>.btn.is-mobile-full {
  -webkit-box-flex: 0;
  flex: 0 0 100%;
  max-width: 100%;
}
```
