### ISSUE TITLE
ボタン内のズレを解消

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#66]
NotoSansでボタン内が若干ずれる問題の解決（Win7 Chrome）

before

![musubii-test-17072601](https://user-images.githubusercontent.com/9658016/28605482-043552ac-720d-11e7-8127-c59d5059d9db.png)

```scss
.btn {
  padding: 0.75em 1em;
  line-height: 1;
}
```

after

![musubii-test-17072602](https://user-images.githubusercontent.com/9658016/28605495-289358ec-720d-11e7-8c50-dba2cf4c307b.png)

```scss
.btn {
  padding: 0.5em 1em;
  > .text,
  > .icon {
    vertical-align: middle;
  }
}
```
同時にvertical-alignも調整している。
他のフォントやアイコンの組み合わせで影響があるかもしれないので確認する。
