### ISSUE TITLE
inputがiOSでダサいのをなんとかする

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#7]

**Comment by qrac** [comment]
```scss
.input[type="text"],
.input[type="search"],
.input[type="url"],
.input[type="email"],
.input[type="tel"],
.input[type="password"],
.input[type="datetime-local"],
.input[type="date"],
.input[type="month"],
.input[type="week"],
.input[type="time"],
.input[type="number"],
.textarea {
  appearance: none;
}
```
