### ISSUE TITLE
ボタン内の高さをline-heightで調整

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#70]
#9 #27 #65 #66 からのボタン改修

> ボタンをFlexboxで組むとiOSのinputが内容のセンター寄せできなくなるはなく

という理由でinline-block化したが、`padding`と`line-height: 1;`で組むとアイコンやフォントによって内容高さが揃わない問題がしばしば見られる。 

```scss
.btn {
  height: 2.5em;
  padding: 0 1em;
  line-height: 2.5em;
}
```

という書き方で解消できないか、フォント・サイズ変化やクロスブラウザで問題が検証。特にNotosans・YuGothic・Material-icons・FontAwesomeの組み合わせ、FirefoxやIE表示の場合に注意。

※ただし、その場合はボタン内が改行されるデザインには対応できなくなり、プロジェクトごとに書くことにはなると思われる。

| before | after |
|:---:|:---:|
|  ![17073101](https://user-images.githubusercontent.com/9658016/28760871-8307f658-75e5-11e7-9216-e85431e02ff2.png) |  ![17073102](https://user-images.githubusercontent.com/9658016/28760879-8e9152c6-75e5-11e7-8796-590cb0aef540.png) |
