### ISSUE TITLE
Layout / Grid：残幅を分配するFlexを追加

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#75]
```scss
.is-mobile-flex {
  flex: 1 1 auto;
  max-width: 100%;
}
```
