### ISSUE TITLE
Utility/ Deco：Position Stickyの追加

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#77]
Position Stickyをよく使うので追加を検討。

追従ヘッダーに利用する場合、Fixedと違い下の要素に余白を作る必要がなくなる。

テーブルのヘッドにも利用価値あり。

```SCSS
.is-sticky-top {
    position: sticky;
    top: 0;
}

.is-sticky-right {
    position: sticky;
    right: 0;
}

.is-sticky-bottom {
    position: sticky;
    bottom: 0;
}

.is-sticky-left {
    position: sticky;
    left: 0;
}
```
