### ISSUE TITLE
Module / Form：ラベルの調整

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#80]
`.field > .label`の調整CSSを書き忘れているので、`label`で括ったオブジェクトが左に寄ってしまっている。

```scss
.field > .label {
  margin-left: 0.5em;
  margin-bottom: 0.5em;
}
```

**Comment by qrac** [comment]
直下にはラベル以外にも様々な要素を置く可能性があるため、全称セレクタに変更。

```scss
.field {
  display: flex;
  flex-wrap: wrap;
  margin-left: -0.5em;
  margin-bottom: -0.5em;
  > * {
    margin-left: 0.5em;
    margin-bottom: 0.5em;
  }
}
```
