### ISSUE TITLE
Utility：Deco / Justifyの追加

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#85]
テキストブロックで使用頻度の高い`text-align: justify;`を追加。

```scss
.is-justify {
    text-align: justify;
}
```
