### ISSUE TITLE
Module / Text：リンク下線へのトランジション付与

### ISSUE THREAD

**Issue by qrac** [qrac/musubii#94]
リンク下線にトランジションをかけるか検討。ボタンなどのhoverは一貫して0.12sかけているが、リンク下線にはかけていない。

下線は位置調整や装飾のし辛さからtext-decorationではなくborderで描いているのでトランジションをかけること自体はできる。

面積が小さい影響か、同じ0.12sでは変化を若干遅く感じるので0.08s〜0.1sあたりでボタンと印象が揃わないか検証。気のせいという可能性もあるので、日をまたいでチェック。

また、追加によって無用な打ち消しを招いてしまわないかなどの悪影響も確認。

```scss
.text.is-link {
    transition: ease-out 0.12s;
}

.text.is-link-reverse {
    transition: ease-out 0.12s;
}
```

一般的なフレームワークの例も参考にする

- [Bootstrap](https://getbootstrap.com/docs/4.0/getting-started/introduction/)：トランジションなし
- [Semantic UI](https://semantic-ui.com/globals/site.html)：ベースの時点では下線自体表示されない
- [Foundation](https://foundation.zurb.com/sites/docs/typography-base.html)：ベースの時点では下線自体表示されない
- [Bulma](https://bulma.io/documentation/elements/content/)：ベースの時点では下線自体表示されない
